"""RAG orchestration pipeline for TenderLens (Milestone 8).

Wires together the retrieval, context-building, and LLM-generation layers into
a single, testable ``question → answer`` pipeline:

    query
    → :class:`~retrieval.retrieval_service.RetrievalService`
    → :class:`~context.context_builder.ContextBuilder`
    → prompt
    → :class:`~generation.provider.LLMProvider`
    → :class:`RAGResult`

No retrieval, embedding, context-building, or LLM-provider logic is duplicated
here.  All three dependencies are injected at construction time, making the
pipeline fully unit-testable with fakes/mocks.

Custom exceptions
-----------------
:class:`EmptyQueryError`
    Raised when :meth:`RAGPipeline.answer` receives an empty or
    whitespace-only query.

Typical usage::

    from retrieval.retrieval_service import RetrievalService
    from retrieval.vector_store import VectorStore
    from context.context_builder import ContextBuilder
    from generation.fake_provider import FakeLLMProvider
    from pipeline.rag_pipeline import RAGPipeline

    store = VectorStore()
    service = RetrievalService(vector_store=store)
    builder = ContextBuilder()
    provider = FakeLLMProvider()

    pipeline = RAGPipeline(
        retrieval_service=service,
        context_builder=builder,
        llm_provider=provider,
    )
    result = pipeline.answer("What is the contract value?")
    print(result.answer)
    print(result.sources)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

from context.context_builder import ContextBuilder
from generation.provider import LLMProvider
from retrieval.retrieval_service import RetrievalService
from retrieval.vector_store import SearchResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PROMPT_TEMPLATE: str = (
    "You are an expert analyst for public tender documents.\n"
    "Answer the question using ONLY the evidence provided below. "
    "Do not use any outside knowledge.\n"
    "If the evidence does not contain enough information to answer "
    "the question, say so explicitly.\n\n"
    "QUESTION:\n{question}\n\n"
    "EVIDENCE:\n{evidence}\n\n"
    "ANSWER:"
)


# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------


class EmptyQueryError(ValueError):
    """Raised when :meth:`RAGPipeline.answer` receives an empty or whitespace-only query."""


# ---------------------------------------------------------------------------
# Result model
# ---------------------------------------------------------------------------


@dataclass
class RAGResult:
    """Structured result returned by :meth:`RAGPipeline.answer`.

    Attributes:
        query:   The original, unmodified query string supplied by the caller.
        answer:  The response generated by the :class:`~generation.provider.LLMProvider`.
        sources: The :class:`~retrieval.vector_store.SearchResult` objects
                 retrieved from the vector store and used as evidence.
                 Metadata (rank, score, chunk_id, document_id, page,
                 chunk_index, text) is preserved verbatim.
    """

    query: str
    answer: str
    sources: list[SearchResult] = field(default_factory=list)


# ---------------------------------------------------------------------------
# RAGPipeline
# ---------------------------------------------------------------------------


class RAGPipeline:
    """Orchestrates the full RAG question-answering flow.

    All three dependencies are injected so the pipeline can be tested in
    isolation without touching FAISS, real embeddings, or live LLM APIs.

    Args:
        retrieval_service: A :class:`~retrieval.retrieval_service.RetrievalService`
            instance used to fetch relevant evidence chunks for a query.
        context_builder:   A :class:`~context.context_builder.ContextBuilder`
            instance used to format retrieved chunks into an evidence string.
        llm_provider:      An :class:`~generation.provider.LLMProvider` instance
            used to generate the final answer from the constructed prompt.

    Raises:
        EmptyQueryError: If *query* is empty or whitespace-only (raised by
            :meth:`answer`, not at construction time).
    """

    def __init__(
        self,
        retrieval_service: RetrievalService,
        context_builder: ContextBuilder,
        llm_provider: LLMProvider,
    ) -> None:
        self._retrieval_service: RetrievalService = retrieval_service
        self._context_builder: ContextBuilder = context_builder
        self._llm_provider: LLMProvider = llm_provider

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def answer(
        self,
        query: str,
        top_k: int = 5,
        document_id: Optional[str] = None,
    ) -> RAGResult:
        """Run the full RAG pipeline for *query* and return a structured result.

        Steps:
        1. Validate that *query* is non-empty / non-whitespace.
        2. Retrieve the top-*top_k* evidence chunks via :attr:`_retrieval_service`.
        3. Build a structured evidence context via :attr:`_context_builder`.
        4. Construct a deterministic prompt containing the question, evidence,
           and an instruction to answer using only the supplied evidence.
        5. Generate an answer via :attr:`_llm_provider`.
        6. Return a :class:`RAGResult` preserving the query, answer, and
           retrieved sources.

        Args:
            query:       Natural-language question to answer.
            top_k:       Maximum number of evidence chunks to retrieve.
                         Passed through to :meth:`~retrieval.retrieval_service.RetrievalService.search`.
            document_id: Optional document filter passed through to
                         :meth:`~retrieval.retrieval_service.RetrievalService.search`.
                         When ``None``, all indexed documents are searched.

        Returns:
            A :class:`RAGResult` containing:
            - ``query``   – the original (unmodified) query string.
            - ``answer``  – the LLM-generated response string.
            - ``sources`` – the list of :class:`~retrieval.vector_store.SearchResult`
              objects used as evidence (metadata preserved).

        Raises:
            EmptyQueryError: If *query* is empty or whitespace-only.
            Any exception raised by :attr:`_retrieval_service` or
            :attr:`_llm_provider` propagates unchanged (e.g.
            :class:`~retrieval.vector_store.StoreNotFoundError`,
            :class:`~generation.provider.EmptyPromptError`).
        """
        # --- 1. Validate query -------------------------------------------
        if not isinstance(query, str) or not query.strip():
            raise EmptyQueryError(
                "answer() requires a non-empty query string; "
                f"got an empty or whitespace-only value: {query!r}"
            )

        logger.debug(
            "RAGPipeline.answer: query=%r top_k=%d document_id=%r",
            query[:80],
            top_k,
            document_id,
        )

        # --- 2. Retrieve evidence ----------------------------------------
        sources: list[SearchResult] = self._retrieval_service.search(
            query=query,
            top_k=top_k,
            document_id=document_id,
        )

        logger.debug("RAGPipeline: retrieved %d source(s).", len(sources))

        # --- 3. Build context --------------------------------------------
        built = self._context_builder.build(sources)

        # --- 4. Construct deterministic prompt ---------------------------
        prompt: str = _PROMPT_TEMPLATE.format(
            question=query,
            evidence=built.context_string,
        )

        logger.debug(
            "RAGPipeline: prompt constructed (length=%d).", len(prompt)
        )

        # --- 5. Generate answer ------------------------------------------
        generated_answer: str = self._llm_provider.generate(prompt)

        logger.debug("RAGPipeline: answer generated (length=%d).", len(generated_answer))

        # --- 6. Return structured result ---------------------------------
        return RAGResult(
            query=query,
            answer=generated_answer,
            sources=sources,
        )
